DROP TABLE IF EXISTS `book` CASCADE;
CREATE TABLE book (
    id BIGINT AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    genre VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);